set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b                      # unbind the default prefix key
set-option -g prefix C-a        # set the prefix key to Ctrl+a
bind-key C-a send-prefix        # bind Ctrl+a to send the prefix key

set -g base-index 1             # start windows numbering at 1

unbind '"' 
unbind '%'
bind | split-window -h          # split window horizontally
bind - split-window -v          # split window vertically

bind r source-file ~/.tmux.conf # reload config